version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default
      - service-proxy
    restart: always
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - ./data/certs:/etc/nginx/certs
    restart: always
    networks:
      - default
      - service-proxy
networks:
    service-proxy:
       external: true